server:
  port: ${SERVER_PORT}

spring:
  application:
    name: OrderFlow-Produto
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

orderflow:
  integracao:
    estoque-url: ${ESTOQUE_URL}
