server:
  port: 8085

spring:
  application:
    name: OrderFlow-Pedido
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

orderflow:
  integracao:
    cliente-url: http://localhost:8081
    estoque-url: http://localhost:8082
    produto-url: http://localhost:8086
