server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: OrderFlow-Logistica
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
